version: '3'

services:
  nginx:
    container_name: 42-container-nginx
    image: 42-image-nginx
    build:
      context: requirements/nginx
    ports:
      - '443:443'
    volumes:
      - 42-volume-wordpress:/var/www/wordpress
    restart: always
    networks:
      - 42-network

  wordpress:
    container_name: 42-container-wordpress
    image: 42-image-wordpress
    build:
      context: requirements/wordpress
    env_file:
      - .env
    volumes:
      - 42-volume-wordpress:/var/www/wordpress
    restart: always
    networks:
      - 42-network

  mariadb:
    container_name: 42-container-mariadb
    image: 42-image-mariadb
    build:
      context: requirements/mariadb
    volumes:
      - 42-volume-mariadb:/var/www/mysql
    env_file:
      - .env
    restart: always
    networks:
      - 42-network

networks:
  42-network:
  
volumes:
  42-volume-wordpress:
  42-volume-mariadb:
