version: '3'

services:
  nginx:
    container_name: nginx
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - 42-network
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - 42-network
    env_file: .env
    restart: always 
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - 42-network
    depends_on:
      - mariadb
    restart: always
    expose: 
      - "9000"

networks:
  42-network:
  
volumes:
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/rohoarau/data/wordpress
  mariadb:
    driver_opts:
      type: none
      o: bind
      device: /home/rohoarau/data/mariadb
