version: '3'

services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - ./.env
    expose: 
      - "3306" 
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - ./.env
    expose:
      - "9000"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always
  
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always

networks:
  inception:

volumes:
  wordpress:
    driver_opts:
      type: 'bridge'
      o: 'bind'
      device: '/home/rohoarau/data/wordpress'
  mariadb:
    driver_opts:
      type: 'bridge'
      o: 'bind'
      device: '/home/rohoarau/data/mariadb'
