CREATE DATABASE IF NOT EXISTS $MARIADB_DB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

GRANT ALL ON $MARIADB_DB.* TO '$MARIADB_ROOT'@'localhost' IDENTIFIED BY '$MARIADB_ROOT_PWD' WITH GRANT OPTION;

GRANT ALL ON $MARIADB_DB.* TO '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PWD';

FLUSH PRIVILEGES;

EXIT;
